services:
  - type: web
    name: railwaymanagement
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn railwaymanagement.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: railwaymanagement.settings
      - key: PYTHON_VERSION
        value: 3.11.11
